### ISSUE TITLE
Error with open non existing dataset folder

### ISSUE THREAD

**Issue by yashma052** [AminovE99/asyncio-prntscrScrapper#2]
iPhone:~/scrp# python3 scrapper.py
0 seconds passed
3 seconds passed
Traceback (most recent call last):
  File "/root/scrp/scrapper.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/scrp/scrapper.py", line 62, in main
    await asyncio.gather(*tasks)
  File "/root/scrp/scrapper.py", line 35, in scrape_pictures
    with open(file, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/scrp/dataset/SoQ0Rbps.jpg'

**Comment by AminovE99** [comment]
@yashma052 , Hello!
Thank you for using my service!
Try to update my repository. I added commit (https://github.com/AminovE99/asyncio-prntscrScrapper/commit/2836e152f4bd2f6efe652bd34cd02af6afcf9fd5) that ignored my dataset folder!
It should decide your problem!
